#!/usr/bin/env node
// Flora_Pac by @leaskh
// www.leaskh.com, i@leaskh.com
// Based on chnroutes project (by Numb.Majority@gmail.com)

var path = require('path'),
    exec = require('child_process').exec,
    rootPath = path.dirname(module.filename);

function makePac(routes) {
    var strPac = '';
    for (var i in routes) {
        console.log(routes[i]);
    }
}

exec(
    'node ' + rootPath + '/bestroutetb/minifier.js',
    function(error, stdout, stderr) {
        if (error !== null || !stdout) {
            console.log('Exec Error: ' + error);
            return;
        }
        console.log(stderr);
        //makePac(JSON.parse(stdout));
    }
);
